### ISSUE TITLE
Badges object polluting developer console in Chrome

### ISSUE THREAD

**Issue by alexlibby** [tetarchus/storybook-addon-badges#40]
I've been using your storybook-addon-badges package for a while, and it's working very well in Storybook 8.2.9. However, I have noticed something that has made me a little curious:

If I run up Storybook (using default URL of localhost:6006), and browse from component page to component page, I see a badges object logged to console for each page I visit:

![image](https://github.com/user-attachments/assets/1e48db3a-e406-498e-8917-cfae0cad5718)

It's not causing me any issues and everything is running, but I'm wondering if there is a way to turn it off please, at least until I need it if not permanently? It's polluting the console log area a little too often - it would be great to only have it displayed when needed...

Any thoughts please?

For info - I'm using Chrome, Storybook 8.2.9, and the set up has one custom badge showing on each component page.

**Comment by tetarchus** [comment]
Apologies, I hadn't merged the latest changes fixing that - v1.0.3 should not pollute the console.

**Comment by alexlibby** [comment]
You star - thankyou! It works perfectly now :-)
